version: "3"
services:
    superset:
        hostname: superset
        container_name: superset
        image: 'apache/superset:2.1.0'  # latest image as of 2021-11-08
        environment:
            SUPERSET_SECRET_KEY: 'data_analytics'
            SESSION_COOKIE_SAMESITE: 'None'
            SESSION_COOKIE_SECURE: 'False'
            SESSION_COOKIE_HTTPONLY: 'False'
            CSRF_ENABLED: 'False'
        ports:
            - "8088:8088"
        networks:
            - data_analytics_project
        restart: on-failure
        env_file: .env
        volumes:
            - superset_home:/app/superset_home
networks:
  data_analytics_project:
    external: true
volumes:
  superset_home:
    external: false