version: "3"
services:
    # object storage
    minio:
        hostname: myminio
        container_name: minio_container
        image: 'bitnami/minio:2021' # latest image as of 2021-11-08
        environment:
            MINIO_ACCESS_KEY: data_analytics
            MINIO_SECRET_KEY: data_analytics
        restart: always
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - 'minio:/data'
        networks:
            - data_analytics_project
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myminio:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
volumes:
    minio:

networks:
  data_analytics_project:
    external: true